import = ["./gruvbox-hard.toml"]

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font.normal]
family = "FiraCode Nerd Font Mono"

[font]
size = 12

[selection]
save_to_clipboard = true

[cursor.style]
blinking = "on"

