[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "lsd --all --long --color=always --group-dirs first {}"

[[session]]
name = "boost"
path = "~/github.com/boost-legal"
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "lsd --all --long --color=always --group-dirs first {}"

[[session]]
name = "hum api"
path = "~/github.com/inqw-qtxr/hum/src/api"
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "lsd --all --long --color=always --group-dirs first {}"

[[session]]
name = "hum client"
path = "~/github.com/inqw-qtxr/hum/src/client"
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "lsd --all --long --color=always --group-dirs first {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "lsd --all --long --color=always --group-dirs first {}"

[[session]]
name = "sesh"
path = "~/dotfiles/sesh"
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "cat ~/dotfiles/sesh/sesh.toml"
