# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Editor Configuration
if command -v nvim &> /dev/null; then
  export EDITOR=nvim
else
  export EDITOR=vi
fi

# Environment Variables
export GPG_TTY=$(tty)
export PYTHONDONTWRITEBYTECODE=1
export HOMEBREW_NO_ENV_HINTS=1

# Path Configuration
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="$PATH:/Users/williamhicks/bin"
export GOPATH="$HOME/go/bin"
export PATH="$PATH:$GOPATH"
export RUBY_PATH="$HOME/ruby-3.0.3/"
export RUBY_BIN="$RUBY_PATH/bin"
export PATH="$PATH:$RUBY_BIN"
export PATH="$PATH:$RUBY_PATH"

# NVM Configuration
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# Google Cloud SDK
if [ -f '/Users/williamhicks/Downloads/google-cloud-sdk/path.zsh.inc' ]; then
  . '/Users/williamhicks/Downloads/google-cloud-sdk/path.zsh.inc'
fi
if [ -f '/Users/williamhicks/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then
  . '/Users/williamhicks/Downloads/google-cloud-sdk/completion.zsh.inc'
fi

# Aliases
alias vim="$EDITOR"

# Completions
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
source <(fzf --zsh)

